In [1]:
import numpy as np
import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin


In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed

reason1  reason2  reason3  reason4  Month Value  Day of the week  \
0          0        0        0        1            7                1   
1          0        0        0        0            7                1   
2          0        0        0        1            7                2   
3          1        0        0        0            7                3   
4          0        0        0        1            7                3   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                2   
696        1        0        0        0            5                2   
697        1        0        0        0            5                3   
698        0        0        0        1            5                3   
699        0        0        0        1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                 30          0         2     1                          4  
1                 31          0         1     0                          0  
2                 31          0         0     0                          2  
3                 24          0         2     0                          4  
4                 30          0         2     1                          2  
..               ...        ...       ...   ...                        ...  
695               22          1         2     0                          8  
696               24          0         1     2                          3  
697               25          1         0     0                          8  
698               25          1         0     0                          2  
699               25          0         1     1                          2  

[700 rows x 15 columns]

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism']=targets

In [7]:
data_preprocessed

reason1  reason2  reason3  reason4  Month Value  Day of the week  \
0          0        0        0        1            7                1   
1          0        0        0        0            7                1   
2          0        0        0        1            7                2   
3          1        0        0        0            7                3   
4          0        0        0        1            7                3   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                2   
696        1        0        0        0            5                2   
697        1        0        0        0            5                3   
698        0        0        0        1            5                3   
699        0        0        0        1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
695               22          1         2     0                          8   
696               24          0         1     2                          3   
697               25          1         0     0                          8   
698               25          1         0     0                          2   
699               25          0         1     1                          2   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 16 columns]

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
data_preprocessed=data_preprocessed.drop(['Absenteeism Time in Hours','Daily Work Load Average','Distance to Work'],axis=1)
unscaled_inputs=data_preprocessed.iloc[:,:-1]
unscaled_inputs

reason1  reason2  reason3  reason4  Month Value  Day of the week  \
0          0        0        0        1            7                1   
1          0        0        0        0            7                1   
2          0        0        0        1            7                2   
3          1        0        0        0            7                3   
4          0        0        0        1            7                3   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                2   
696        1        0        0        0            5                2   
697        1        0        0        0            5                3   
698        0        0        0        1            5                3   
699        0        0        0        1            5                3   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 12 columns]

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.array(np.mean(X[self.columns]))
        self.var_ = np.array(np.var(X[self.columns]))
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]



In [12]:
unscaled_inputs.columns.values

array(['reason1', 'reason2', 'reason3', 'reason4', 'Month Value',
       'Day of the week', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [13]:
columns_to_scale=[ 'Month Value',
        'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets']

In [14]:
absenteeism_scale=CustomScaler(columns_to_scale)

In [15]:
absenteeism_scale.fit(unscaled_inputs)
scaled_inputs = absenteeism_scale.transform(unscaled_inputs)

In [16]:
from sklearn.model_selection import train_test_split


In [17]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
reg=LogisticRegression()

In [20]:
reg.fit(x_train,y_train)

LogisticRegression()

In [21]:
reg.score(x_train,y_train)

0.775

In [22]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [23]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [24]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.775

In [25]:
reg.coef_

array([[ 2.79988218,  0.93534521,  3.09632467,  0.85318008,  0.16640374,
        -0.05777182,  0.611268  , -0.1647515 ,  0.26892738, -0.08036821,
         0.36096419, -0.28638684]])

In [26]:
reg.intercept_

array([-1.57217553])

In [27]:
feature_name=unscaled_inputs.columns.values
feature_name

array(['reason1', 'reason2', 'reason3', 'reason4', 'Month Value',
       'Day of the week', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [28]:
summary_table=pd.DataFrame(columns=['Feature Name'],data=feature_name.T)
summary_table

Feature Name
0                  reason1
1                  reason2
2                  reason3
3                  reason4
4              Month Value
5          Day of the week
6   Transportation Expense
7                      Age
8          Body Mass Index
9                Education
10                Children
11                    Pets

In [29]:
summary_table['coefficient']=np.transpose(reg.coef_)
summary_table

Feature Name  coefficient
0                  reason1     2.799882
1                  reason2     0.935345
2                  reason3     3.096325
3                  reason4     0.853180
4              Month Value     0.166404
5          Day of the week    -0.057772
6   Transportation Expense     0.611268
7                      Age    -0.164751
8          Body Mass Index     0.268927
9                Education    -0.080368
10                Children     0.360964
11                    Pets    -0.286387

In [30]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]

In [31]:
summary_table.sort_index()

Feature Name  coefficient
0                Intercept    -1.572176
1                  reason1     2.799882
2                  reason2     0.935345
3                  reason3     3.096325
4                  reason4     0.853180
5              Month Value     0.166404
6          Day of the week    -0.057772
7   Transportation Expense     0.611268
8                      Age    -0.164751
9          Body Mass Index     0.268927
10               Education    -0.080368
11                Children     0.360964
12                    Pets    -0.286387

In [32]:
summary_table['Odds ratio']=np.exp(summary_table['coefficient'])
summary_table

Feature Name  coefficient  Odds ratio
1                  reason1     2.799882   16.442709
2                  reason2     0.935345    2.548093
3                  reason3     3.096325   22.116516
4                  reason4     0.853180    2.347099
5              Month Value     0.166404    1.181050
6          Day of the week    -0.057772    0.943865
7   Transportation Expense     0.611268    1.842767
8                      Age    -0.164751    0.848104
9          Body Mass Index     0.268927    1.308560
10               Education    -0.080368    0.922777
11                Children     0.360964    1.434712
12                    Pets    -0.286387    0.750972
0                Intercept    -1.572176    0.207593

In [33]:
summary_table.sort_values(by='Odds ratio',ascending=False)

Feature Name  coefficient  Odds ratio
3                  reason3     3.096325   22.116516
1                  reason1     2.799882   16.442709
2                  reason2     0.935345    2.548093
4                  reason4     0.853180    2.347099
7   Transportation Expense     0.611268    1.842767
11                Children     0.360964    1.434712
9          Body Mass Index     0.268927    1.308560
5              Month Value     0.166404    1.181050
6          Day of the week    -0.057772    0.943865
10               Education    -0.080368    0.922777
8                      Age    -0.164751    0.848104
12                    Pets    -0.286387    0.750972
0                Intercept    -1.572176    0.207593

In [34]:
reg.score(x_test,y_test)

0.7428571428571429

In [35]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.73645446, 0.26354554],
       [0.60866226, 0.39133774],
       [0.41135756, 0.58864244],
       [0.80340301, 0.19659699],
       [0.07228579, 0.92771421],
       [0.3164599 , 0.6835401 ],
       [0.31285946, 0.68714054],
       [0.13360905, 0.86639095],
       [0.79765425, 0.20234575],
       [0.75065661, 0.24934339],
       [0.48084035, 0.51915965],
       [0.19792873, 0.80207127],
       [0.07763508, 0.92236492],
       [0.71035264, 0.28964736],
       [0.30669496, 0.69330504],
       [0.57535995, 0.42464005],
       [0.54013184, 0.45986816],
       [0.5711829 , 0.4288171 ],
       [0.38179745, 0.61820255],
       [0.04840317, 0.95159683],
       [0.69821798, 0.30178202],
       [0.79411798, 0.20588202],
       [0.39566497, 0.60433503],
       [0.42359877, 0.57640123],
       [0.26620227, 0.73379773],
       [0.75660355, 0.24339645],
       [0.51411974, 0.48588026],
       [0.86879099, 0.13120901],
       [0.1995932 , 0.8004068 ],
       [0.78451205, 0.21548795],
       [0.

In [36]:
predicted_proba[:,1:]

array([[0.26354554],
       [0.39133774],
       [0.58864244],
       [0.19659699],
       [0.92771421],
       [0.6835401 ],
       [0.68714054],
       [0.86639095],
       [0.20234575],
       [0.24934339],
       [0.51915965],
       [0.80207127],
       [0.92236492],
       [0.28964736],
       [0.69330504],
       [0.42464005],
       [0.45986816],
       [0.4288171 ],
       [0.61820255],
       [0.95159683],
       [0.30178202],
       [0.20588202],
       [0.60433503],
       [0.57640123],
       [0.73379773],
       [0.24339645],
       [0.48588026],
       [0.13120901],
       [0.8004068 ],
       [0.21548795],
       [0.3737439 ],
       [0.68687894],
       [0.69154171],
       [0.54281886],
       [0.20588202],
       [0.50731074],
       [0.21012245],
       [0.74379229],
       [0.4358105 ],
       [0.59249922],
       [0.22721166],
       [0.43390986],
       [0.21637129],
       [0.39625319],
       [0.81524562],
       [0.5700738 ],
       [0.69138   ],
       [0.274

In [37]:
import pickle 

In [38]:
with open ('model','wb') as file:
    pickle.dump(reg,file)
with open ('scaler','wb') as file:
    pickle.dump(absenteeism_scale,file)  