In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv('real_estate_price_size_year.csv')

In [3]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [4]:
x=data[['size','year']]
y=data['price']

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)
x_scaled=scaler.transform(x)


In [6]:
reg=LinearRegression()

In [7]:
reg.fit(x_scaled,y)

LinearRegression()

In [8]:
reg.intercept_

292289.4701599997

In [9]:
reg.coef_

array([67501.57614152, 13724.39708231])

In [10]:
r2=reg.score(x_scaled,y)
r2

0.7764803683276793

In [11]:
x_scaled.shape

(100, 2)

In [12]:
n=x.shape[0]
p=x.shape[1]
r2_adj=1-(1-r2)*(n-1)/(n-p-1)
r2_adj

0.77187171612825

In [13]:
new_data=[[750,2009]]

new_data_scaled=scaler.transform(new_data)
new_data_scaled

array([[-0.34752816, -0.76509206]])

In [14]:
reg.predict(new_data_scaled)

array([258330.34465995])

In [15]:
from sklearn.feature_selection import f_regression

In [16]:
f_regression=f_regression(x_scaled,y)

In [20]:
p_value=f_regression[1]
p_value.round(3)

array([0.   , 0.357])

In [22]:
summary=pd.DataFrame(index={'size','year'})
summary['cofficient']=reg.coef_
summary['p-values']=p_value.round(3)

In [23]:
summary

cofficient  p-values
size  67501.576142     0.000
year  13724.397082     0.357