In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

### データを読み込み、従属変数と独立変数を定義する


In [3]:
raw_data=pd.read_csv('real_estate_price_size_year.csv')
raw_data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [4]:
data=raw_data.copy()

In [16]:
y=data['price']
x=data[['size','year']]

### データに対して標準化を行う


In [46]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

### 切片、係数、自由度、自由度修正済みを求める


In [47]:
reg=LinearRegression()
reg.fit(x_scaled,y)


LinearRegression()

In [48]:
reg.coef_

array([67501.57614152, 13724.39708231])

In [49]:
reg.intercept_

292289.4701599997

In [51]:
r2=reg.score(x_scaled,y)
r2

0.7764803683276793

In [52]:
n=x.shape[0]
p=x.shape[1]
r2_adj=1-(1-r2)*(n-1)/(n-p-1)
r2_adj

0.77187171612825

### サイズ750，年2009のデータを作成し、標準化をした上で予測する


In [53]:
predict=[[750,2009]]
result=scaler.transform(predict)

In [54]:
reg.predict(result)

array([258330.34465995])

### f値からp値を求め、データの有意性について考察する

In [58]:
from sklearn.feature_selection import f_regression
f_regression=f_regression(x_scaled,y)
p_value=f_regression[1]
p_value

array([8.12763222e-31, 3.57340758e-01])

In [60]:
p_value.round(3)

array([0.   , 0.357])

年の列は有意ではない

In [70]:
summary=pd.DataFrame(index={'size','year'})
summary['coef']=reg.coef_
summary['p-value']=p_value.round(3)
summary

coef  p-value
size  67501.576142    0.000
year  13724.397082    0.357